services:
  letsencrypt:
    container_name: letsencrypt
    hostname: letsencrypt
    build: ../build
    restart: unless-stopped
    environment:
      STANDALONE: true
      DATA_VOLUME: certificates
      EMAIL: john@doe.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../build/config/domains.conf:/config/domains.conf:ro
      - certificates:/etc/letsencrypt:rw
volumes:
  certificates:
