services:
  letsencrypt_webroot:
    container_name: letsencrypt_webroot
    hostname: letsencrypt_webroot
    build: ../build
    restart: unless-stopped
    environment:
      EMAIL: john@doe.com
      WEBROOT: /var/www/certbot
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ../build/config/domains.conf:/config/domains.conf:ro
      - certificates:/etc/letsencrypt:rw
      - webroot:/var/www/certbot:rw
  nginx_letsencrypt_webroot:
    container_name: nginx_letsencrypt_webroot
    hostname: nginx_letsencrypt_webroot
    image: nginx:1.27.4-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - webroot:/var/www/certbot:ro
volumes:
  certificates:
  webroot:
